### PR TITLE
Match on keywords in the launcher

### PR DESCRIPTION
**Pull request by pedrocr**
In the launcher match not only on the program name but also on the keywords specified in the desktop file.

Replaces #23 and depends on https://github.com/zonyitoo/rust-ini/pull/60

### CODE REVIEW

**Comment by pedrocr** [comment]
Right now I just matched keywords and names all together. It may make sense to make name matches always sort above keyword matches. That shouldn't be too hard.

**Comment by pedrocr** [comment]
This should be a pretty clean version now. The matching is moved to its own little struct and the matches are now unique and mix in the fuzzy matching score with the priority levels for names versus keywords.

**Comment by kennylevinsen** [comment]
I very much like how this turned out. Thanks a lot!

**Comment by pedrocr** [comment]
You're more than welcome.

You were slightly too fast though. The rust-ini PR was just merged so depending on my git branch in cargo is no longer needed :)

**Comment by kennylevinsen** [comment]
I took care of that by adding a dependency edit/update to the branch before I manually merged it. :)

(I could also have rewritten the commit with the dependency, but eh, it's not *wrong* that it depended on your branch first.)

**Comment by pedrocr** [comment]
Ah, great then. I was going to rewrite history to hide that but I guess
that's also correct.

**Pull request merged**
